### ISSUE TITLE
No Issue - just thanks ;)

### ISSUE THREAD

**Issue by transmitthis** [bluescan/tacit-texview#13]
Just spend way too long looking for a HDR viewer, eventually came to github and found your release.

All I needed was a quick way to see my HDR's to decide which to import into Blender, the Content View is ideal for me.

So just thanks for doing whatever it is you do. It's appreciated. 

Kind Regards TT

**Comment by bluescan** [comment]
Nice to hear. Thanks transmitthis. Glad you found the project :)
